Repository PowerShell/PowerShell-Docker, pull requests merged in 2019-11, with the labels that each got.

#313 Install pester if it isn't already installed
  .vsts-ci/phase.yml
  build.ps1
  vsts-ci.yml
Labels: AutoMerge, Issue-Enhancement

#317 Disabled clearlinux so community build passes for now
  tools/buildHelper/buildHelper.psm1
Labels: AutoMerge, Issue-Bug

#306 Changed lots of docs
  MAINTAINERS
  assets/README.powershell.md
  docs/development.md
Labels: Issue-Enhancement

#325 Skip pushing when using ACR
  tests/container.tests.ps1
Labels: Issue-Enhancement

#318 Refactoring parts of repo
  .poshchan/settings.json
  .vsts-ci/misc-analysis.yml
  .vsts-ci/templates/credscan.yml
  assets/README.powershellcommunity.md
  build.ps1
  createAllManifests.ps1
  createManifest.ps1
  setupVsts.ps1
  tests/container.tests.ps1
  tools/buildHelper/buildHelper.psm1
  vsts-ci.yml
Labels: Issue-Enhancement

#327 Typo fix
  docs/SECURITY.md
Labels: AutoMerge
