Repository PowerShell/PowerShell-Docker, pull requests merged in 2020-01, with the labels that each got.

#345 Slim down some of the final images
  MAINTAINERS
  release/community-stable/archlinux/docker/Dockerfile
  release/community-stable/blackarch/docker/Dockerfile
  release/community-stable/kali-rolling/docker/Dockerfile
  release/community-stable/oraclelinux/docker/Dockerfile
  release/community-stable/oraclelinux/meta.json
  release/community-stable/parrot/docker/Dockerfile
  release/preview/centos7/test-deps/docker/Dockerfile
  release/preview/centos8/test-deps/docker/Dockerfile
  release/preview/debian9/docker/Dockerfile
  release/preview/ubuntu16.04/docker/Dockerfile
  release/preview/ubuntu18.04/docker/Dockerfile
  release/servicing/arm32v7/docker/Dockerfile
  release/servicing/debian9/docker/Dockerfile
  release/servicing/ubuntu16.04/docker/Dockerfile
  release/servicing/ubuntu18.04/docker/Dockerfile
  release/stable/arm32v7/docker/Dockerfile
  release/stable/centos7/test-deps/docker/Dockerfile
  release/stable/debian9/docker/Dockerfile
  release/stable/ubuntu16.04/docker/Dockerfile
  release/stable/ubuntu18.04/docker/Dockerfile
Labels: Issue-Enhancement

#354 Add terms page
  docs/terms.md
Labels: Issue-Enhancement

#357 Initial refactor of CI for LTS release
  .vsts-ci/phase.yml
  .vsts-ci/stage.yml
  .vsts-ci/vsts-arm-ci.yml
  build.ps1
  release/preview/nanoserver/meta.json
  release/stable/nanoserver/meta.json
  tools/buildHelper/buildHelper.psm1
  vsts-ci.yml
Labels: Needs: Triage :mag:

#367 Add ncurses to the image so clear works
  release/preview/centos8/docker/Dockerfile
Labels: Issue-Enhancement, dependencies

#364 Update README.powershell.md
  assets/README.powershell.md
Labels: Issue-Enhancement
