Repository PowerShell/PowerShell-Docker, pull requests merged in 2020-10, with the labels that each got.

#497 Remove Alpine 3.8 and 3.9
  .github/dependabot.yml
  release/lts/alpine39/dependabot/Dockerfile
  release/lts/alpine39/docker/Dockerfile
  release/lts/alpine39/getLatestTag.ps1
  release/lts/alpine39/meta.json
  release/lts/alpine39/test-deps/docker/Dockerfile
  release/lts/alpine39/test-deps/meta.json
  release/preview/alpine39/dependabot/Dockerfile
  release/preview/alpine39/docker/Dockerfile
  release/preview/alpine39/meta.json
  release/preview/alpine39/test-deps/docker/Dockerfile
  release/preview/alpine39/test-deps/meta.json
  release/stable/alpine38/dependabot/Dockerfile
  release/stable/alpine38/docker/Dockerfile
  release/stable/alpine38/getLatestTag.ps1
  release/stable/alpine38/meta.json
  release/stable/alpine38/test-deps/docker/Dockerfile
  release/stable/alpine38/test-deps/meta.json
  release/stable/alpine39/dependabot/Dockerfile
  release/stable/alpine39/docker/Dockerfile
  release/stable/alpine39/meta.json
  release/stable/alpine39/test-deps/docker/Dockerfile
  release/stable/alpine39/test-deps/meta.json
Labels: hacktoberfest-accepted

#498 Changing fulltags for windowsserver preview, lts, and stable
  release/lts/windowsservercore/getLatestTag.ps1
  release/lts/windowsservercore/meta.json
  release/lts/windowsservercore1809/docker/Dockerfile
  release/lts/windowsservercore1809/meta.json
  release/lts/windowsservercore1903/docker/Dockerfile
  release/lts/windowsservercore1903/meta.json
  release/lts/windowsservercore1909/docker/Dockerfile
  release/lts/windowsservercore1909/meta.json
  release/lts/windowsservercore2004/dependabot/Dockerfile
  release/lts/windowsservercore2004/docker/Dockerfile
  release/lts/windowsservercore2004/meta.json
  release/preview/windowsservercore/getLatestTag.ps1
  release/preview/windowsservercore1809/docker/Dockerfile
  release/preview/windowsservercore1809/meta.json
  release/preview/windowsservercore1903/docker/Dockerfile
  release/preview/windowsservercore1903/meta.json
  release/preview/windowsservercore1909/docker/Dockerfile
  release/preview/windowsservercore1909/meta.json
  release/preview/windowsservercore2004/dependabot/Dockerfile
  release/preview/windowsservercore2004/docker/Dockerfile
  release/preview/windowsservercore2004/meta.json
  release/stable/windowsservercore/getLatestTag.ps1
  release/stable/windowsservercore1809/docker/Dockerfile
  release/stable/windowsservercore1809/meta.json
  release/stable/windowsservercore1903/docker/Dockerfile
  release/stable/windowsservercore1903/meta.json
  release/stable/windowsservercore1909/docker/Dockerfile
  release/stable/windowsservercore1909/meta.json
  release/stable/windowsservercore2004/docker/Dockerfile
  release/stable/windowsservercore2004/meta.json
Labels: Issue-Enhancement, hacktoberfest-accepted

#503 remove usage of `fromtag`
  release/community-stable/amazonlinux/test-deps/docker/Dockerfile
  release/community-stable/kalilinux/docker/Dockerfile
  release/preview/alpine310/docker/Dockerfile
  release/preview/alpine310/test-deps/docker/Dockerfile
  release/preview/alpine311/test-deps/docker/Dockerfile
Labels: Waiting on Author

#494 Fedora 32
  release/stable/fedora32/docker/Dockerfile
  release/stable/fedora32/meta.json
Labels: Issue-Enhancement

#508 Fix OracleLinux image: Missing latest tag from official Oracle Linux repository
  release/community-stable/oraclelinux/docker/Dockerfile
  release/community-stable/oraclelinux/meta.json
Labels: hacktoberfest-accepted

#506 Fix ArchLinux image: Dockerfile COPY failed with no such file or directory for gss-ntlmssp package file
  release/community-stable/archlinux/docker/Dockerfile
  release/community-stable/archlinux/meta.json
Labels: Issue-Bug, hacktoberfest-accepted

#507 Fix BlackArch image: Dockerfile COPY failed with no such file or directory for gss-ntlmssp package file
  release/community-stable/blackarch/docker/Dockerfile
  release/community-stable/blackarch/meta.json
Labels: Issue-Bug, hacktoberfest-accepted

#512 Remove debian fulltags
  release/lts/debian10/docker/Dockerfile
  release/lts/debian10/getLatestTag.ps1
  release/lts/debian10/meta.json
  release/lts/debian9/docker/Dockerfile
  release/lts/debian9/getLatestTag.ps1
  release/lts/debian9/meta.json
  release/preview/debian10/docker/Dockerfile
  release/preview/debian10/getLatestTag.ps1
  release/preview/debian10/meta.json
  release/preview/debian9/docker/Dockerfile
  release/preview/debian9/getLatestTag.ps1
  release/preview/debian9/meta.json
  release/stable/debian10/docker/Dockerfile
  release/stable/debian10/getLatestTag.ps1
  release/stable/debian10/meta.json
  release/stable/debian9/docker/Dockerfile
  release/stable/debian9/getLatestTag.ps1
  release/stable/debian9/meta.json
Labels: Issue-Enhancement

#510 Community-Stable OracleLinux: Add Dependabot capability
  .github/dependabot.yml
  release/community-stable/oraclelinux/meta.json
Labels: Issue-Enhancement, hacktoberfest-accepted
